Feat: 도서상태 전체조회
nhnacademy-be7-55G-COM/55G.COM-shop pull request #162
Opened 2024-11-06 04:25 UTC by Jung-won-seok

- 도서상태 전체조회 기능구현, 테스트
- 카테고리 requestDto, responseDto : parentCategoryId ->  parentCategoryName으로 수정

2024-11-07 13:37 UTC, DooYoungHo approved these changes

2024-11-08 05:11 UTC, FlowerfulFort requested changes
테스트만 바꿔주시면 빌드가 됩니다.

2024-11-08 05:11 UTC, FlowerfulFort commented on src/test/java/shop/S5G/shop/controller/bookstatus/BookStatusControllerTest.java
> +
test 패키지 아래에 있는 SecurityTest를 참고해서 `@WebMvcTest`랑 `@Import`문을 넣어주세요

2024-11-08 05:11 UTC, FlowerfulFort commented on src/test/java/shop/S5G/shop/repository/bookstatus/BookStatusRepositoryTest.java
> +    private BookStatusQuerydslRepositoryImpl bookStatusQuerydslRepository;
QuerydslImpl 클래스를 autowire할 필요 없습니다.

2024-11-08 05:11 UTC, FlowerfulFort commented on src/test/java/shop/S5G/shop/repository/bookstatus/BookStatusRepositoryTest.java
> +    private BookStatusQuerydslRepositoryImpl bookStatusQuerydslRepository;
위에 있는 bookrepositorytest도 바꿔주세요

2024-11-08 05:11 UTC, FlowerfulFort commented on src/main/java/shop/S5G/shop/repository/bookstatus/qdsl/impl/BookStatusQuerydslRepositoryImpl.java
> +    private EntityManager em;
이거 EntityManager가 이렇게 주입이 되는건가요? 궁금해서

2024-11-08 05:11 UTC, FlowerfulFort commented on src/main/java/shop/S5G/shop/repository/bookstatus/qdsl/impl/BookStatusQuerydslRepositoryImpl.java
> +    }
EntityManager를 `@PersistenceContext`로 주입받으면 thread-safe 하다고 합니다.

jpaQueryFactory를 사용하실 예정이면 jpaQueryFactory를 빈으로 등록해서 가져오는게 메모리 절약과 성능에 도움될것 같습니다.

2024-11-08 06:29 UTC, FlowerfulFort approved these changes

2024-11-08 06:29 UTC, merged