Feature/book
nhnacademy-be7-55G-COM/55G.COM-shop pull request #191
Opened 2024-11-12 07:13 UTC by Gyubin-Han

2024-11-12 07:45 UTC, DooYoungHo approved these changes

2024-11-12 07:45 UTC, DooYoungHo commented on src/main/java/shop/s5g/shop/entity/Book.java
>  public class Book {
Book Entity에 publishedDate 없어진건가용??

2024-11-12 07:45 UTC, DooYoungHo commented on src/main/java/shop/s5g/shop/entity/Book.java
> +    public Book(Long bookId, Publisher publisher, BookStatus bookStatus, String title,
여기도 매개변수에는 있는데 안에는 publishedDate가 안 보입니다!

2024-11-12 08:02 UTC, Gyubin-Han commented on src/main/java/shop/s5g/shop/entity/Book.java
>  public class Book {
아뇨! publishedDate 있습니다!

2024-11-12 19:40 UTC, bobo1006 approved these changes

2024-11-13 00:15 UTC, FlowerfulFort reviewed
:)

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/entity/BookImage.java
>      private Book book;
lazy fetch여야 할것같아요

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/entity/BookAuthor.java
> +    private Author author;
lazy fetch로 바꿔주세요

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/entity/Book.java
> +        BigDecimal discountRate, boolean isPacked, int stock, Long views, LocalDateTime createdAt) {
이 생성자가 왜 생긴건지 궁금합니다

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/entity/Book.java
> +@Builder
`@Builder`가 왜 위로 갔는지 궁금합니다

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/entity/Author.java
> +    private Profile profile;
lazy fetch로 바꿔주세요

2024-11-13 00:15 UTC, FlowerfulFort commented on src/main/java/shop/s5g/shop/controller/BookController.java
> +//
book controller는 아예 안쓰는건가요?

2024-11-13 00:22 UTC, FlowerfulFort requested changes
1

2024-11-13 00:32 UTC, Gyubin-Han commented
> 1

감사합니다! 수정했습니다!

2024-11-13 00:35 UTC, Minjeong63 approved these changes

2024-11-13 00:37 UTC, FlowerfulFort approved these changes
:D

2024-11-13 00:37 UTC, merged